<?php

/**
 * @file
 * Contains drupalpro_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_help().
 */
function drupalpro_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ai_content_archive module.
    case 'help.page.drupalpro_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom blocks used on the Drupalpro.dk website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function drupalpro_blocks_theme($existing, $type, $theme, $path) {
  return [
    'block__drupalpro_top_image' => [
      'render element' => 'elements',
      'base hook' => 'block',
    ],
    'block__drupalpro_facts' => [
      'base hook' => 'block',
      'fact_modules' => 0,
      'fact_developers_worldwide' => 0,
      'fact_jobs_denmark' => 0,
      'fact_drupalpro_members' => 0
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function drupalpro_blocks_preprocess_block(&$variables) {
  switch ($variables['base_plugin_id']) {
    case 'drupalpro_top_image':
      $variables['site_logo'] = '';
      if ($variables['content']['site_logo']['#uri']) {
        $variables['site_logo'] = $variables['content']['site_logo']['#uri'];
      }
      $variables['top_text'] = '';
      if ($variables['content']['top_text']['#markup']) {
        $variables['top_text'] = $variables['content']['top_text']['#markup'];
      }
      $variables['top_image'] = '';
      if ($variables['content']['top_image']['#uri']) {
        $uri = $variables['content']['top_image']['#uri'];
        $variables['top_image'] =  ImageStyle::load('top_image')->buildUrl($uri);
      }
      break;

    case 'drupalpro_facts':
      $variables['fact_modules'] = $variables['content']['fact_modules'];
      $variables['fact_developers_worldwide'] = $variables['content']['fact_developers_worldwide'];
      $variables['fact_jobs_denmark'] = $variables['content']['fact_jobs_denmark'];
      $variables['fact_drupalpro_members'] = $variables['content']['fact_drupalpro_members'];
      break;
  }
}